---

- name: Ensure essential python packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libffi-dev
    - libssl-dev
    - libyaml-dev
    - libyaml-cpp-dev
    - python-dev
    - python-pip
    - python-setuptools
    - python-virtualenv
  tags:
    - skip_ansible_lint # ANSIBLE0010

- name: Download AWS cfn-bootstrap
  become: yes
  get_url:
    url: "https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-{{ aws_bootstrap.version }}.tar.gz"
    dest: "/usr/local/src/aws-cfn-bootstrap-{{ aws_bootstrap.version }}.tar.gz"

- name: Extract AWS cfn-bootstrap
  become: yes
  unarchive:
    remote_src: yes
    src: "/usr/local/src/aws-cfn-bootstrap-{{ aws_bootstrap.version }}.tar.gz"
    dest: /usr/local/src/
    creates: "/usr/local/src/aws-cfn-bootstrap-{{ aws_bootstrap.version | regex_replace('^(.*?)-[0-9]+$', '\\1') }}/setup.py"

- name: Install AWS cfn-bootstrap
  become: yes
  command: "easy_install /usr/local/src/aws-cfn-bootstrap-{{ aws_bootstrap.version | regex_replace('^(.*?)-[0-9]+$', '\\1') }}"
  args:
    creates: /usr/local/bin/cfn-init

- name: Prepare landing folder
  become: yes
  file:
    path: /bootstrap
    mode: 0777
    state: directory

- name: Prepare for teleportation
  shell: "tar --exclude .git:.vagrant:self.tgz -czf self.tgz $(ls -d ansible Makefile 2>/dev/null)"
  args:
    chdir: "{{ root_dir }}"
    creates: "{{ root_dir }}/self.tgz"
  delegate_to: localhost
  run_once: true
  tags:
    - skip_ansible_lint # ANSIBLE0006

- name: Teleport yourself to the machine
  copy:
    src: "{{ root_dir }}/self.tgz"
    dest: /tmp
  register: teleport_status

- name: Unpack
  become: yes
  unarchive:
    remote_src: yes
    src: "/tmp/self.tgz"
    dest: /bootstrap
  when: teleport_status.changed

- name: Install local python deps
  command: make init
  args:
    chdir: /bootstrap
    creates: /bootstrap/.venv

- name: Install additional extras
  include: extras/htpasswd.yml
  when: "'htpasswd' in aws_bootstrap.extras"

- name: Install additional extras
  include: extras/postgresql.yml
  when: "'postgresql' in aws_bootstrap.extras"

- name: Install additional extras
  include: extras/mysql.yml
  when: "'mysql' in aws_bootstrap.extras"

- name: Copy scripts
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/bootstrap/{{ item }}"
    mode: 0644
  with_items:
    - bootstrap.inc.sh
