---

- name: Ensure essential python packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libffi-dev
    - libssl-dev
    - libyaml-dev
    - libyaml-cpp-dev
    - python-dev
    - python-pip
    - python-setuptools
    - python-virtualenv
  tags:
    - skip_ansible_lint # ANSIBLE0010

- name: Download AWS cfn-bootstrap
  become: yes
  get_url:
    url: "https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-{{ aws_bootstrap.version }}.tar.gz"
    dest: "/usr/local/src/aws-cfn-bootstrap-{{ aws_bootstrap.version }}.tar.gz"

- name: Extract AWS cfn-bootstrap
  become: yes
  unarchive:
    remote_src: yes
    src: "/usr/local/src/aws-cfn-bootstrap-{{ aws_bootstrap.version }}.tar.gz"
    dest: /usr/local/src/
    creates: "/usr/local/src/aws-cfn-bootstrap-{{ aws_bootstrap.version | regex_replace('^(.*?)-[0-9]+$', '\\1') }}/setup.py"

- name: Install AWS cfn-bootstrap
  become: yes
  command: "/usr/bin/env python setup.py install"
  args:
    creates: /usr/local/bin/cfn-init
    chdir: "/usr/local/src/aws-cfn-bootstrap-{{ aws_bootstrap.version | regex_replace('^(.*?)-[0-9]+$', '\\1') }}"

- name: Prepare landing folder
  become: yes
  file:
    path: /bootstrap
    mode: 0777
    state: directory

- name: Teleportation
  include: "teleport_{{ aws_bootstrap.teleport_mode }}.yml"

- name: Install additional extras
  include: extras/htpasswd.yml
  when: "'htpasswd' in aws_bootstrap.extras"

- name: Install additional extras
  include: extras/postgresql.yml
  when: "'postgresql' in aws_bootstrap.extras"

- name: Install additional extras
  include: extras/mysql.yml
  when: "'mysql' in aws_bootstrap.extras"

- name: Copy scripts
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/bootstrap/{{ item }}"
    mode: 0644
  with_items:
    - bootstrap.inc.sh
